import { 
  Tag, Gamepad2, Headphones, Keyboard, Mouse, Printer, Wifi, Camera, Speaker, 
  Smartphone, Watch, ShoppingBag, Gift, Star, Heart, Award, Crown, Shield, 
  Rocket, Sparkles, Flame, Leaf, Sun, Moon, Cloud, Umbrella, Anchor, Compass, 
  Map, Globe, Flag, Bookmark, Briefcase, Clock, Calendar, Bell, Mail, 
  MessageSquare, Phone, Video, Music, Film, BookOpen, FileText, Folder, 
  Database, Server, Terminal, Settings, Wrench, Hammer, PenTool, Scissors, 
  Paintbrush, Palette, Monitor, Laptop, Cpu, Box, Package, LucideIcon,
  Joystick, Tv, Key, Code, Bot, Armchair, Zap, HardDrive, MemoryStick, CircuitBoard, Droplets
} from "lucide-react";

// Mapping of icon keys to Lucide icon components
export const iconMap: Record<string, LucideIcon> = {
  'tag': Tag,
  'gamepad2': Gamepad2,
  'joystick': Joystick,
  'headphones': Headphones,
  'keyboard': Keyboard,
  'mouse': Mouse,
  'printer': Printer,
  'wifi': Wifi,
  'camera': Camera,
  'speaker': Speaker,
  'smartphone': Smartphone,
  'watch': Watch,
  'shopping-bag': ShoppingBag,
  'gift': Gift,
  'star': Star,
  'heart': Heart,
  'award': Award,
  'crown': Crown,
  'shield': Shield,
  'rocket': Rocket,
  'sparkles': Sparkles,
  'flame': Flame,
  'leaf': Leaf,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'umbrella': Umbrella,
  'anchor': Anchor,
  'compass': Compass,
  'map': Map,
  'globe': Globe,
  'flag': Flag,
  'bookmark': Bookmark,
  'briefcase': Briefcase,
  'clock': Clock,
  'calendar': Calendar,
  'bell': Bell,
  'mail': Mail,
  'message-square': MessageSquare,
  'phone': Phone,
  'video': Video,
  'music': Music,
  'film': Film,
  'book-open': BookOpen,
  'file-text': FileText,
  'folder': Folder,
  'database': Database,
  'server': Server,
  'terminal': Terminal,
  'settings': Settings,
  'wrench': Wrench,
  'hammer': Hammer,
  'pen-tool': PenTool,
  'scissors': Scissors,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'monitor': Monitor,
  'laptop': Laptop,
  'cpu': Cpu,
  'box': Box,
  'package': Package,
  'tv': Tv,
  'key': Key,
  'code': Code,
  'bot': Bot,
  'armchair': Armchair,
  'zap': Zap,
  'hard-drive': HardDrive,
  'memory-stick': MemoryStick,
  'circuit-board': CircuitBoard,
  'droplets': Droplets,
};

// Get icon component from key, defaults to Tag
export function getIconFromKey(iconKey?: string): LucideIcon {
  if (!iconKey) return Tag;
  return iconMap[iconKey] || Tag;
}
